import { contextBridge, ipcRenderer } from 'electron'
import type { DeviceHubApi } from '../src/shared/types'

const api: DeviceHubApi = {
  reminders: {
    list: () => ipcRenderer.invoke('reminders:list'),
    create: (input) => ipcRenderer.invoke('reminders:create', input),
    update: (id, updates) => ipcRenderer.invoke('reminders:update', id, updates),
    remove: (id) => ipcRenderer.invoke('reminders:remove', id),
  },
  goals: {
    list: () => ipcRenderer.invoke('goals:list'),
    create: (input) => ipcRenderer.invoke('goals:create', input),
    update: (id, updates) => ipcRenderer.invoke('goals:update', id, updates),
    logProgress: (id, delta, note) => ipcRenderer.invoke('goals:logProgress', id, delta, note),
    history: (id) => ipcRenderer.invoke('goals:history', id),
    remove: (id) => ipcRenderer.invoke('goals:remove', id),
  },
  budget: {
    listCategories: () => ipcRenderer.invoke('budget:listCategories'),
    createCategory: (input) => ipcRenderer.invoke('budget:createCategory', input),
    removeCategory: (id) => ipcRenderer.invoke('budget:removeCategory', id),
    listTransactions: (month) => ipcRenderer.invoke('budget:listTransactions', month),
    createTransaction: (input) => ipcRenderer.invoke('budget:createTransaction', input),
    removeTransaction: (id) => ipcRenderer.invoke('budget:removeTransaction', id),
    summary: (month) => ipcRenderer.invoke('budget:summary', month),
  },
  canvas: {
    getSettings: () => ipcRenderer.invoke('canvas:getSettings'),
    saveSettings: (settings) => ipcRenderer.invoke('canvas:saveSettings', settings),
    sync: () => ipcRenderer.invoke('canvas:sync'),
    listCached: () => ipcRenderer.invoke('canvas:listCached'),
    setLocalCompletion: (id, completed) => ipcRenderer.invoke('canvas:setLocalCompletion', id, completed),
  },
  notifications: {
    getGoogleAuthStatus: () => ipcRenderer.invoke('notifications:getGoogleAuthStatus'),
    saveGoogleCredentials: (clientId, clientSecret) =>
      ipcRenderer.invoke('notifications:saveGoogleCredentials', clientId, clientSecret),
    connectGoogle: () => ipcRenderer.invoke('notifications:connectGoogle'),
    disconnectGoogle: () => ipcRenderer.invoke('notifications:disconnectGoogle'),
    getDigest: () => ipcRenderer.invoke('notifications:getDigest'),
    refreshDigest: () => ipcRenderer.invoke('notifications:refreshDigest'),
    markAsRead: (id) => ipcRenderer.invoke('notifications:markAsRead', id),
  },
  calendar: {
    getEvents: () => ipcRenderer.invoke('calendar:getEvents'),
    refreshEvents: () => ipcRenderer.invoke('calendar:refreshEvents'),
    createEvent: (input) => ipcRenderer.invoke('calendar:createEvent', input),
    deleteEvent: (id) => ipcRenderer.invoke('calendar:deleteEvent', id),
  },
  fitness: {
    listFood: (date) => ipcRenderer.invoke('fitness:listFood', date),
    createFood: (input) => ipcRenderer.invoke('fitness:createFood', input),
    removeFood: (id) => ipcRenderer.invoke('fitness:removeFood', id),
    listExercise: (date) => ipcRenderer.invoke('fitness:listExercise', date),
    createExercise: (input) => ipcRenderer.invoke('fitness:createExercise', input),
    removeExercise: (id) => ipcRenderer.invoke('fitness:removeExercise', id),
    dailySummary: (date) => ipcRenderer.invoke('fitness:dailySummary', date),
    getCalorieTarget: () => ipcRenderer.invoke('fitness:getCalorieTarget'),
    setCalorieTarget: (target) => ipcRenderer.invoke('fitness:setCalorieTarget', target),
  },
  assistant: {
    getStatus: () => ipcRenderer.invoke('assistant:getStatus'),
    saveApiKey: (provider, apiKey) => ipcRenderer.invoke('assistant:saveApiKey', provider, apiKey),
    setProvider: (provider) => ipcRenderer.invoke('assistant:setProvider', provider),
    getHistory: () => ipcRenderer.invoke('assistant:getHistory'),
    sendMessage: (content) => ipcRenderer.invoke('assistant:sendMessage', content),
    clearHistory: () => ipcRenderer.invoke('assistant:clearHistory'),
  },
  oura: {
    getStatus: () => ipcRenderer.invoke('oura:getStatus'),
    saveToken: (token) => ipcRenderer.invoke('oura:saveToken', token),
    sync: () => ipcRenderer.invoke('oura:sync'),
    listCached: () => ipcRenderer.invoke('oura:listCached'),
  },
  profile: {
    getName: () => ipcRenderer.invoke('profile:getName'),
    setName: (name) => ipcRenderer.invoke('profile:setName', name),
  },
  weather: {
    getSettings: () => ipcRenderer.invoke('weather:getSettings'),
    saveSettings: (input) => ipcRenderer.invoke('weather:saveSettings', input),
    sync: () => ipcRenderer.invoke('weather:sync'),
    getCached: () => ipcRenderer.invoke('weather:getCached'),
  },
  spotify: {
    getStatus: () => ipcRenderer.invoke('spotify:getStatus'),
    saveCredentials: (clientId, clientSecret) => ipcRenderer.invoke('spotify:saveCredentials', clientId, clientSecret),
    connect: () => ipcRenderer.invoke('spotify:connect'),
    disconnect: () => ipcRenderer.invoke('spotify:disconnect'),
    sync: () => ipcRenderer.invoke('spotify:sync'),
    getCached: () => ipcRenderer.invoke('spotify:getCached'),
    getPlaybackState: () => ipcRenderer.invoke('spotify:getPlaybackState'),
    controlPlayback: (action) => ipcRenderer.invoke('spotify:controlPlayback', action),
  },
  strava: {
    getStatus: () => ipcRenderer.invoke('strava:getStatus'),
    saveCredentials: (clientId, clientSecret) => ipcRenderer.invoke('strava:saveCredentials', clientId, clientSecret),
    connect: () => ipcRenderer.invoke('strava:connect'),
    disconnect: () => ipcRenderer.invoke('strava:disconnect'),
    sync: () => ipcRenderer.invoke('strava:sync'),
    getCached: () => ipcRenderer.invoke('strava:getCached'),
    createActivity: (input) => ipcRenderer.invoke('strava:createActivity', input),
  },
  microsoft: {
    getStatus: () => ipcRenderer.invoke('microsoft:getStatus'),
    saveCredentials: (clientId, clientSecret) => ipcRenderer.invoke('microsoft:saveCredentials', clientId, clientSecret),
    connect: () => ipcRenderer.invoke('microsoft:connect'),
    disconnect: () => ipcRenderer.invoke('microsoft:disconnect'),
    sync: () => ipcRenderer.invoke('microsoft:sync'),
    getCached: () => ipcRenderer.invoke('microsoft:getCached'),
  },
  linkedin: {
    getProfile: () => ipcRenderer.invoke('linkedin:getProfile'),
    saveCredentials: (clientId, clientSecret) => ipcRenderer.invoke('linkedin:saveCredentials', clientId, clientSecret),
    connect: () => ipcRenderer.invoke('linkedin:connect'),
    disconnect: () => ipcRenderer.invoke('linkedin:disconnect'),
  },
  plaid: {
    getSettings: () => ipcRenderer.invoke('plaid:getSettings'),
    saveSettings: (input) => ipcRenderer.invoke('plaid:saveSettings', input),
    createLinkToken: () => ipcRenderer.invoke('plaid:createLinkToken'),
    exchangePublicToken: (publicToken, institutionName) =>
      ipcRenderer.invoke('plaid:exchangePublicToken', publicToken, institutionName),
    sync: () => ipcRenderer.invoke('plaid:sync'),
    listItems: () => ipcRenderer.invoke('plaid:listItems'),
    listAccounts: () => ipcRenderer.invoke('plaid:listAccounts'),
    listTransactions: () => ipcRenderer.invoke('plaid:listTransactions'),
    removeItem: (itemId) => ipcRenderer.invoke('plaid:removeItem', itemId),
  },
  system: {
    notify: (title, body) => ipcRenderer.invoke('system:notify', title, body),
  },
}

contextBridge.exposeInMainWorld('api', api)
